name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        with:
          merge-method: merge
          auto-merge-minimum-reviewers: 0
          auto-merge-delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
